let producto = {
    id: 0,              // Int
    nombre: "",         // String
    modelo: "",         // String
    precio: 0.0,        // Float
    cantidad: 0,        // Int
    descuento: 0,       // Int
    estrellas: 0,       // Int
    esNuevo: false,     // Bool
    categoria: ""       // String
};


export const productos = [
    {id: 1, nombre: "Producto E 1", modelo: "Modelo EX-001", precio: 100.0, cantidad: 10, descuento: 0, estrellas: 4, esNuevo: false, categoria: "Electrónica"},
    {id: 2, nombre: "Producto E 2", modelo: "Modelo EX-002", precio: 175.0, cantidad: 3, descuento: 30, estrellas: 1, esNuevo: true, categoria: "Electrónica"},
    {id: 3, nombre: "Producto E 3", modelo: "Modelo EX-003", precio: 109.99, cantidad: 5, descuento: 10, estrellas: 3, esNuevo: false, categoria: "Electrónica"},
    {id: 4, nombre: "Producto E 4", modelo: "Modelo EX-004", precio: 349.99, cantidad: 8, descuento: 5, estrellas: 5, esNuevo: false, categoria: "Electrónica"},
    {id: 5, nombre: "Producto E 5", modelo: "Modelo EX-005", precio: 580.0, cantidad: 0, descuento: 10, estrellas: 5, esNuevo: false, categoria: "Electrónica"},
    {id: 6, nombre: "Producto E 6", modelo: "Modelo EX-006", precio: 1199.99, cantidad: 2, descuento: 0, estrellas: 3, esNuevo: true, categoria: "Electrónica"},
    {id: 7, nombre: "Producto E 7", modelo: "Modelo EX-007", precio: 2499.99, cantidad: 15, descuento: 0, estrellas: 2, esNuevo: false, categoria: "Electrónica"},
    {id: 8, nombre: "Producto E 8", modelo: "Modelo EX-008", precio: 3500.0, cantidad: 20, descuento: 20, estrellas: 5, esNuevo: true, categoria: "Electrónica"},
    {id: 9, nombre: "Producto E 9", modelo: "Modelo EX-009", precio: 4000.0, cantidad: 3, descuento: 20, estrellas: 4, esNuevo: false, categoria: "Electrónica"},
    {id: 10, nombre: "Producto E 10", modelo: "Modelo EX-010", precio: 4499.99, cantidad: 4, descuento: 50, estrellas: 4, esNuevo: false, categoria: "Electrónica"},
    {id: 11, nombre: "Producto E 11", modelo: "Modelo EX-011", precio: 2250.50, cantidad: 1, descuento: 10, estrellas: 1, esNuevo: false, categoria: "Electrónica"},
    {id: 12, nombre: "Producto E 12", modelo: "Modelo EX-012", precio: 8850.0, cantidad: 30, descuento: 15, estrellas: 3, esNuevo: true, categoria: "Electrónica"},
    {id: 13, nombre: "Producto E 13", modelo: "Modelo EX-013", precio: 6249.99, cantidad: 8, descuento: 0, estrellas: 2, esNuevo: false, categoria: "Electrónica"},
    {id: 14, nombre: "Producto E 14", modelo: "Modelo EX-014", precio: 10000.0, cantidad: 0, descuento: 0, estrellas: 5, esNuevo: false, categoria: "Electrónica"},
    {id: 15, nombre: "Producto E 15", modelo: "Modelo EX-015", precio: 9009.0, cantidad: 9, descuento: 10, estrellas: 4, esNuevo: false, categoria: "Electrónica"},
    {id: 16, nombre: "Producto M 1", modelo: "Modelo Mo-001", precio: 350.0, cantidad: 15, descuento: 0, estrellas: 3, esNuevo: false, categoria: "Moda"},
    {id: 17, nombre: "Producto M 2", modelo: "Modelo Mo-002", precio: 799.99, cantidad: 12, descuento: 0, estrellas: 4, esNuevo: true, categoria: "Moda"},
    {id: 18, nombre: "Producto M 3", modelo: "Modelo Mo-003", precio: 2499.99, cantidad: 7, descuento: 0, estrellas: 4, esNuevo: false, categoria: "Moda"},
    {id: 19, nombre: "Producto M 4", modelo: "Modelo Mo-004", precio: 5000.0, cantidad: 5, descuento: 0, estrellas: 5, esNuevo: true, categoria: "Moda"},
    {id: 20, nombre: "Producto M 5", modelo: "Modelo Mo-005", precio: 15000.0, cantidad: 2, descuento: 10, estrellas: 5, esNuevo: true, categoria: "Moda"},
    {id: 21, nombre: "Producto M 6", modelo: "Modelo Mo-006", precio: 17000.99, cantidad: 2, descuento: 20, estrellas: 4, esNuevo: false, categoria: "Moda"},
    {id: 22, nombre: "Producto M 7", modelo: "Modelo Mo-007", precio: 4499.99, cantidad: 8, descuento: 50, estrellas: 3, esNuevo: false, categoria: "Moda"},
    {id: 23, nombre: "Producto M 8", modelo: "Modelo Mo-008", precio: 800.0, cantidad: 3, descuento: 5, estrellas: 1, esNuevo: false, categoria: "Moda"},
    {id: 24, nombre: "Producto M 9", modelo: "Modelo Mo-009", precio: 7299.99, cantidad: 1, descuento: 15, estrellas: 2, esNuevo: false, categoria: "Moda"},
    {id: 25, nombre: "Producto M 10", modelo: "Modelo Mo-010", precio: 735.0, cantidad: 1, descuento: 25, estrellas: 2, esNuevo: false, categoria: "Moda"},
    {id: 26, nombre: "Producto M 11", modelo: "Modelo Mo-011", precio: 2000.0, cantidad: 9, descuento: 35, estrellas: 3, esNuevo: true, categoria: "Moda"},
    {id: 27, nombre: "Producto M 12", modelo: "Modelo Mo-012", precio: 25000.0, cantidad: 13, descuento: 10, estrellas: 5, esNuevo: false, categoria: "Moda"},
    {id: 28, nombre: "Producto M 13", modelo: "Modelo Mo-013", precio: 9499.99, cantidad: 5, descuento: 25, estrellas: 4, esNuevo: false, categoria: "Moda"},
    {id: 29, nombre: "Producto M 14", modelo: "Modelo Mo-014", precio: 120.0, cantidad: 0, descuento: 0, estrellas: 1, esNuevo: false, categoria: "Moda"},
    {id: 30, nombre: "Producto M 15", modelo: "Modelo Mo-015", precio: 6700.0, cantidad: 0, descuento: 0, estrellas: 3, esNuevo: true, categoria: "Moda"},
    {id: 31, nombre: "Producto H 1", modelo: "Modelo Ho-001", precio: 400.0, cantidad: 3, descuento: 0, estrellas: 5, esNuevo: false, categoria: "Hogar"},
    {id: 32, nombre: "Producto H 2", modelo: "Modelo Ho-002", precio: 200.0, cantidad: 20, descuento: 20, estrellas: 3, esNuevo: false, categoria: "Hogar"},
    {id: 33, nombre: "Producto H 3", modelo: "Modelo Ho-003", precio: 1500.0, cantidad: 15, descuento: 30, estrellas: 5, esNuevo: false, categoria: "Hogar"},
    {id: 34, nombre: "Producto H 4", modelo: "Modelo Ho-004", precio: 3800.0, cantidad: 14, descuento: 10, estrellas: 3, esNuevo: false, categoria: "Hogar"},
    {id: 35, nombre: "Producto H 5", modelo: "Modelo Ho-005", precio: 5000.0, cantidad: 7, descuento: 5, estrellas: 4, esNuevo: false, categoria: "Hogar"},
    {id: 36, nombre: "Producto H 6", modelo: "Modelo Ho-006", precio: 2000.99, cantidad: 1, descuento: 45, estrellas: 2, esNuevo: false, categoria: "Hogar"},
    {id: 37, nombre: "Producto H 7", modelo: "Modelo Ho-007", precio: 8499.99, cantidad: 8, descuento: 30, estrellas: 1, esNuevo: false, categoria: "Hogar"},
    {id: 38, nombre: "Producto H 8", modelo: "Modelo Ho-008", precio: 7499.99, cantidad: 7, descuento: 10, estrellas: 5, esNuevo: false, categoria: "Hogar"},
    {id: 39, nombre: "Producto H 9", modelo: "Modelo Ho-009", precio: 1000.0, cantidad: 3, descuento: 15, estrellas: 5, esNuevo: false, categoria: "Hogar"},
    {id: 40, nombre: "Producto H 10", modelo: "Modelo Ho-010", precio: 2500.0, cantidad: 3, descuento: 20, estrellas: 4, esNuevo: false, categoria: "Hogar"},
    {id: 41, nombre: "Producto H 11", modelo: "Modelo Ho-011", precio: 6000.0, cantidad: 6, descuento: 35, estrellas: 4, esNuevo: false, categoria: "Hogar"},
    {id: 42, nombre: "Producto H 12", modelo: "Modelo Ho-012", precio: 1200.0, cantidad: 17, descuento: 50, estrellas: 3, esNuevo: false, categoria: "Hogar"},
    {id: 43, nombre: "Producto H 13", modelo: "Modelo Ho-013", precio: 1200.0, cantidad: 25, descuento: 50, estrellas: 3, esNuevo: false, categoria: "Hogar"},
    {id: 44, nombre: "Producto H 14", modelo: "Modelo Ho-014", precio: 9999.99, cantidad: 1, descuento: 10, estrellas: 1, esNuevo: false, categoria: "Hogar"},
    {id: 45, nombre: "Producto H 15", modelo: "Modelo Ho-015", precio: 10000.0, cantidad: 0, descuento: 0, estrellas: 5, esNuevo: false, categoria: "Hogar"},
    {id: 46, nombre: "Producto D 1", modelo: "Modelo Dp-001", precio: 350.0, cantidad: 9, descuento: 0, estrellas: 5, esNuevo: false, categoria: "Deportes"},
    {id: 47, nombre: "Producto D 2", modelo: "Modelo Dp-002", precio: 999.99, cantidad: 11, descuento: 10, estrellas: 4, esNuevo: false, categoria: "Deportes"},
    {id: 48, nombre: "Producto D 3", modelo: "Modelo Dp-003", precio: 2500.0, cantidad: 15, descuento: 15, estrellas: 5, esNuevo: true, categoria: "Deportes"},
    {id: 49, nombre: "Producto D 4", modelo: "Modelo Dp-004", precio: 5000.0, cantidad: 10, descuento: 20, estrellas: 4, esNuevo: false, categoria: "Deportes"},
    {id: 50, nombre: "Producto D 5", modelo: "Modelo Dp-005", precio: 4500.0, cantidad: 24, descuento: 25, estrellas: 5, esNuevo: true, categoria: "Deportes"},
    {id: 51, nombre: "Producto D 6", modelo: "Modelo Dp-006", precio: 875.0, cantidad: 8, descuento: 0, estrellas: 3, esNuevo: false, categoria: "Deportes"},
    {id: 52, nombre: "Producto D 7", modelo: "Modelo Dp-007", precio: 6000.0, cantidad: 2, descuento: 0, estrellas: 5, esNuevo: false, categoria: "Deportes"},
    {id: 53, nombre: "Producto D 8", modelo: "Modelo Dp-008", precio: 4999.99, cantidad: 1, descuento: 15, estrellas: 4, esNuevo: false, categoria: "Deportes"},
    {id: 54, nombre: "Producto D 9", modelo: "Modelo Dp-009", precio: 1250.0, cantidad: 20, descuento: 0, estrellas: 3, esNuevo: false, categoria: "Deportes"},
    {id: 55, nombre: "Producto D 10", modelo: "Modelo Dp-010", precio: 2700.0, cantidad: 15, descuento: 10, estrellas: 1, esNuevo: true, categoria: "Deportes"},
    {id: 56, nombre: "Producto D 11", modelo: "Modelo Dp-011", precio: 7000.0, cantidad: 5, descuento: 10, estrellas: 2, esNuevo: false, categoria: "Deportes"},
    {id: 57, nombre: "Producto D 12", modelo: "Modelo Dp-012", precio: 3200.0, cantidad: 7, descuento: 35, estrellas: 5, esNuevo: false, categoria: "Deportes"},
    {id: 58, nombre: "Producto D 13", modelo: "Modelo Dp-013", precio: 4125.0, cantidad: 34, descuento: 0, estrellas: 4, esNuevo: true, categoria: "Deportes"},
    {id: 59, nombre: "Producto D 14", modelo: "Modelo Dp-014", precio: 3000.0, cantidad: 25, descuento: 60, estrellas: 4, esNuevo: false, categoria: "Deportes"},
    {id: 60, nombre: "Producto D 15", modelo: "Modelo Dp-015", precio: 359.99, cantidad: 10, descuento: 0, estrellas: 3, esNuevo: false, categoria: "Deportes"},
    {id: 61, nombre: "Producto R 1", modelo: "Modelo Ro-001", precio: 500.0, cantidad: 21, descuento: 0, estrellas: 4, esNuevo: true, categoria: "Regalos"},
    {id: 62, nombre: "Producto R 2", modelo: "Modelo Ro-002", precio: 500.0, cantidad: 21, descuento: 15, estrellas: 4, esNuevo: true, categoria: "Regalos"},
    {id: 63, nombre: "Producto R 3", modelo: "Modelo Ro-003", precio: 500.0, cantidad: 1, descuento: 0, estrellas: 4, esNuevo: false, categoria: "Regalos"},
    {id: 64, nombre: "Producto R 4", modelo: "Modelo Ro-004", precio: 500.0, cantidad: 21, descuento: 10, estrellas: 3, esNuevo: true, categoria: "Regalos"},
    {id: 65, nombre: "Producto R 5", modelo: "Modelo Ro-005", precio: 500.0, cantidad: 21, descuento: 0, estrellas: 3, esNuevo: true, categoria: "Regalos"},
    {id: 66, nombre: "Producto R 6", modelo: "Modelo Ro-006", precio: 1500.0, cantidad: 15, descuento: 0, estrellas: 3, esNuevo: true, categoria: "Regalos"},
    {id: 67, nombre: "Producto R 7", modelo: "Modelo Ro-007", precio: 1500.0, cantidad: 15, descuento: 0, estrellas: 5, esNuevo: true, categoria: "Regalos"},
    {id: 68, nombre: "Producto R 8", modelo: "Modelo Ro-008", precio: 1500.0, cantidad: 15, descuento: 20, estrellas: 5, esNuevo: true, categoria: "Regalos"},
    {id: 69, nombre: "Producto R 9", modelo: "Modelo Ro-009", precio: 2700.0, cantidad: 15, descuento: 0, estrellas: 5, esNuevo: true, categoria: "Regalos"},
    {id: 70, nombre: "Producto R 10", modelo: "Modelo Ro-010", precio: 2700.0, cantidad: 2, descuento: 0, estrellas: 2, esNuevo: false, categoria: "Regalos"},
    {id: 71, nombre: "Producto R 11", modelo: "Modelo Ro-011", precio: 2700.0, cantidad: 21, descuento: 30, estrellas: 2, esNuevo: true, categoria: "Regalos"},
    {id: 72, nombre: "Producto R 12", modelo: "Modelo Ro-012", precio: 3800.0, cantidad: 21, descuento: 0, estrellas: 2, esNuevo: true, categoria: "Regalos"},
    {id: 73, nombre: "Producto R 13", modelo: "Modelo Ro-013", precio: 3800.0, cantidad: 4, descuento: 0, estrellas: 4, esNuevo: false, categoria: "Regalos"},
    {id: 74, nombre: "Producto R 14", modelo: "Modelo Ro-014", precio: 3800.0, cantidad: 7, descuento: 0, estrellas: 4, esNuevo: true, categoria: "Regalos"},
    {id: 75, nombre: "Producto R 15", modelo: "Modelo Ro-015", precio: 5000.0, cantidad: 7, descuento: 60, estrellas: 1, esNuevo: true, categoria: "Regalos"}
];
